name: Docker Build

on:
  push:
    branches-ignore:
      master
  pull_request:
    branches:
      - master

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Build API Server docker
        run: docker build --tag api_server:latest .

      - name: Inspect
        run: docker inspect api_server:latest