name: Docker

on: [push]


jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Setup Source For GitHub
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Image for cache
        run: docker pull ghcr.io/cyb3r-jak3/api_server:latest

      - name: Build API Server docker
        run: docker build . --tag ghcr.io/cyb3r-jak3/api_server:latest --cache-from ghcr.io/cyb3r-jak3/api_server:latest

      - name: Inspect
        run: docker inspect ghcr.io/cyb3r-jak3/api_server:latest 

      - name: Push
        if: github.event_name == 'push' && env.BRANCH == 'master'
        run: docker push ghcr.io/cyb3r-jak3/api_server:latest 
  