name: Docker Release

on:
  push:
    branches:
      master


jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Source For GitHub
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Image for cache
        run: docker pull ghcr.io/cyb3r-jak3/api_server:latest

      - name: Build API Server docker
        run: docker build . --tag ghcr.io/cyb3r-jak3/api_server:latest --cache-from ghcr.io/cyb3r-jak3/api_server:latest

      - name: Inspect
        run: docker inspect ghcr.io/cyb3r-jak3/api_server:latest 

      - name: Push
        if: ${{ github.event_name == 'push' }}
        run: docker push ghcr.io/cyb3r-jak3/api_server:latest 
  