name: Docker Check

on: [push]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Check build
          run: docker build . --tag api-server
        - name: Inspect
          run: docker inspect api-server