name: Testing

on: [push]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Docker for GitHub
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username cyb3r-jak3  --password-stdin
    - name: Build API Server docker
      run: docker build . --tag docker.pkg.github.com/cyb3r-jak3/api_server/api_server:latest
    - name: Inspect
      run: docker inspect docker.pkg.github.com/cyb3r-jak3/api_server/api_server:latest
    - name: Push
      run: docker push docker.pkg.github.com/cyb3r-jak3/api_server/api_server:latest


  Python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txts') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements-dev.txt
    - name: Lint with Flake8
      run: flake8 app.py --count --show-source --statistics
    - name: Lint with PyLint
      run: pylint app.py
    - name: Lint with bandit
      run: bandit app.py
    - name: Lint with Python Black
      run: black --check app.py --line-length 80 --diff
    - name: Run Pytests
      run: |
        py.test --cov app test_flask.py -vv
        coverage xml
    - name: Report results to DeepSource
      run: |
        coverage xml
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
      env: 
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}