name: Build & Check

on: [push]


jobs:

  Python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('**/requirements.txt', '**/requirements-dev.txts') }}
  
    - name: Install dependencies
      run: pip install -r requirements-dev.txt

    - name: Lint with Flake8
      run: flake8 app.py --count --show-source --statistics

    - name: Lint with PyLint
      run: pylint app.py

    - name: Lint with Bandit
      run: bandit app.py

    - name: Lint with Python Black
      run: black --check app.py --line-length 80 --diff

    - name: Run Pytests
      run: py.test --cov app test_flask.py -vv

    - name: Report results to DeepSource
      run: |
        coverage xml
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
      env: 
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

  Docker:
    needs: Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Setup Source For GitHub
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Image for cache
        run: docker pull ghcr.io/cyb3r-jak3/api_server:latest

      - name: Build API Server docker
        run: docker build . --tag ghcr.io/cyb3r-jak3/api_server:latest --cache-from ghcr.io/cyb3r-jak3/api_server:latest

      - name: Inspect
        run: docker inspect ghcr.io/cyb3r-jak3/api_server:latest 

      - name: Push
        if: github.event_name == 'push' && env.BRANCH == 'master'
        run: docker push ghcr.io/cyb3r-jak3/api_server:latest
