name: Python

on: [push]

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txts') }}
  
    - name: Install dependencies
      run: pip install --upgrade --upgrade-strategy eager -r requirements-dev.txt

    - name: Lint with Flake8
      run: flake8 app.py --count --show-source --statistics

    - name: Lint with PyLint
      run: pylint app.py

    - name: Lint with Bandit
      run: bandit app.py

    - name: Lint with Python Black
      run: black --check app.py --line-length 80 --diff

    - name: Run Pytests
      run: py.test --cov app test_flask.py -vv

    - name: Report results to DeepSource
      run: |
        coverage xml
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
      env: 
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}